### PR TITLE
Aded amenities to room cards

### LINKED ISSUE #144: Add hotel rooms amenities
Show amenities for each room type in the app, they can be accessed from /HOTEL_ADDRESS/roomTypes.

i32 hotel roomTypes example: https://demo-api.windingtree.com/hotels/0x4Ee2BC4804D1A75AEBa5C76D25cc2c036B136140/roomTypes

### PR DESCRIPTION
**Pull request by skkr**
closes #144 

_* framework update required_ 

image

### CODE REVIEW

**Comment by AugustoL** [comment]
@skkr please make the first word of each amenity uppercase

**Comment by skkr** [comment]
@AugustoL this cames from the server
@MatiasOS FYI

**Comment by skkr** [comment]
image

@AugustoL

**Comment by AugustoL** [comment]
@skkr please solve conflicts

**Pull request merged**
