### PR TITLE
Travis deploys

### PR DESCRIPTION
**Pull request by MatiasOS**
I have made changes to travis, to stay syn with other repos

- Add stages, 
    - test will run on every pr to run tests
    - deploy only run after tag push

### CODE REVIEW

**Comment by MatiasOS** [comment]
Yes, @beogip suggested to  have some nomenclature for tags like {sub-package-name}-{version} and add travis to check the subpackage.

**Comment by JirkaChadima** [comment]
If I had to I'd go with release branches instead of git tags with some prefixes. For example `release/app`, `release/server`. You can protect these branches here on github in any way you want. This branching model seems more flexible to me.

**Comment by MatiasOS** [comment]
I like the idea of deploy based on branchs! What do you think @beogip @AugustoL ?

**Comment by beogip** [comment]
The problem that I see with the branch approach is that you are not going to have a direct commit/tag to make a rollback. To use it we need to  squash commits before making merge with that release branches

**Comment by JirkaChadima** [comment]
I can see the point, but I've actually never done a rollback :-) If you deploy something buggy, just revert some commits, make a release, then revert them back. Or, you know, fix the bugs. If you feel there will be a need for rollback, maybe we should have a QA environment to prevent them from happening.

**Pull request merged**
