### PR TITLE
Updated classnames and styles to match the wt-ui release

### PR DESCRIPTION
**Pull request by skkr**
Related to https://github.com/windingtree/wt-ui/pull/62

These changes will be required after upgrading wt-ui.

### CODE REVIEW

**Comment by skkr** [comment]
Lets wait until the wt-release is ready to merge this.

**Comment by MatiasOS** [comment]
@skkr wt-ui v1.0.0 is ready now.

**Comment by skkr** [comment]
Thanks @MatiasOS , I'll add the framework in a new commit so we can merge all together.

**Comment by MatiasOS** [comment]
@skkr I have make the update of wt-ui in #396

**Comment by skkr** [comment]
@MatiasOS, got it!

**Pull request merged**
