### PR TITLE
Replaced hotel icon with a map in hotel section

### LINKED ISSUE #217: Add a map in the hotel section
Add a component in the app that displays a map with the location of the hotel.

image

A small map should replace the big hotel logo next to the description.

### PR DESCRIPTION
**Pull request by skkr**
Included a map, and adjusted the layout for different viewport sizes

closes #217 

image

### CODE REVIEW

**Comment by skkr** [comment]
@AugustoL we'll need too add an apy key. Do we have one?

**Comment by AugustoL** [comment]
@skkr a gpmaps api key? cant you get one for yourself?

**Comment by skkr** [comment]
@AugustoL not without creating a billing account.

**Comment by skkr** [comment]
@AugustoL used [leaflet](https://leafletjs.com/) instead google. 

image

**Pull request merged**
