### PR TITLE
fix(app): display availability when user change dates or room type

### LINKED ISSUE #367: Display availability of rooms before final checkout
I tried to book a room and the app let me fill all the information including Etherum address from which I will pay and then showed message that we are full. It would be nice to show the availability as soon as possible which is when user selects room and date. Especially if there is last few rooms available.

### PR DESCRIPTION
**Pull request by PabloAlice**
this fix #367 
samples:
image

image

### CODE REVIEW

**Comment by skkr** [comment]
I would remove the available message and will only keep the other one.

I would change the message to something like "Sorry, the room you selected is not available on these dates"

@czervenka what do you think?

**Comment by MatiasOS** [comment]
The `is available` message is a good think, always is a good to have confirmation from the interface.  The text is not the best, but maybe something like  ` {Icon} - Room is un/available for selected dates` is better.

**Comment by PabloAlice** [comment]
I think that @MatiasOS is right, but I don't know who can decide this.
ie: if I select some dates, and It's not available among them, I will see an error message, and if I select another pair of dates I would like to see a confirmation message that let me think "dates are ok, move forward"

**Comment by skkr** [comment]
Just asked Robin. IMO in this case is redundant info. It's OK to inform the user, but is always good to keep things simple for them.

**Comment by skkr** [comment]
Just checked with a colleague, and he agrees with me.

Also I didn't noticed before, but the check icon in the selectos should be only in the selected room button.

**Comment by czervenka** [comment]
The best practice seems to me to hide / disable the rest of booking form till the user selects the room type and date range. If we do so, the application can indicate that everything is ok (the room is available at the dates) by simply enabling / showing the rest of the booking form.

On the other case, when the room is not available, it would be nice to tell the user what to do. For example: "The room is not available for this date. Try a different room or select a different date, please."

**Comment by czervenka** [comment]
Anyway, if you would like to keep the success message I would love to see a better message there. Something like: "The room is still free for you. Hurry up! Our smart contract respects only one rule: First come, first served."

**Comment by skkr** [comment]
Pablo, please give a look to the check icon issue (you can create one).

Regarding this PR, we can do what Robin think is best.

**Comment by PabloAlice** [comment]
http://recordit.co/jD5oj6l1Mt

I didn't like how looks the success message when hiding/showing the form, that's why I remove it.

let me know what you think @czervenka @skkr

**Comment by skkr** [comment]
@PabloAlice we should keep the form always visible, you can disable de fields as Rob bin suggested but the form never should hide.

**Comment by PabloAlice** [comment]
@czervenka Thank you for the feedback!
@skkr let me know if it's fine

http://recordit.co/mHCPfDpZ1F

**Comment by PabloAlice** [comment]
http://recordit.co/tZ2qohGCz0

**Comment by czervenka** [comment]
The last version looks great! Thanks for your effort and patience :)

**Pull request merged**
