### PR TITLE
Updated transaction instructions in payment email template

### LINKED ISSUE #249: Send rigth TX instructions for Lif
@skkr The email that the guests receive with instructions for lif contains only one tx and it should show any value since the value is 0 for both txs it needs to send.

It should be smth like this:

Payment instructions
--
In order to pay for your room, please send this transaction in order.

To: tx[0].to
Data: tx[0].data

To: tx[1].to
Data: tx[1].data

### PR DESCRIPTION
**Pull request by skkr**
Closes #249 

image

### CODE REVIEW

**Comment by AugustoL** [comment]
Remove the send sectiom please, no value is transfered. Only two txs with to and data

**Comment by skkr** [comment]
@AugustoL done!

image

**Comment by skkr** [comment]
From @MatiasOS 
>Please use a loop on the array txs or an if to avoid tx[1] if not exists.
>Because the instructions are used for eth and Lif, thus some times there is only one and other times are two

**Comment by skkr** [comment]
@MatiasOS please review the last commit.

**Pull request merged**
